# contestants file


SQUARE_SIZE = 20
NUM_SQUARES_WIDTH = 50
NUM_SQUARES_HEIGHT = 25
WINDOW_WIDTH = SQUARE_SIZE * NUM_SQUARES_WIDTH
WINDOW_HEIGHT = SQUARE_SIZE * NUM_SQUARES_HEIGHT

EMPTY_VALUE = 0
MINE_VALUE = 1

# FLAG_MEASUREMENTS

FLAG_POS = ()
