import pygame
# contestants file


SQUARE_SIZE = 20
NUM_SQUARES_WIDTH = 50
NUM_SQUARES_HEIGHT = 25
WINDOW_WIDTH = SQUARE_SIZE * NUM_SQUARES_WIDTH
WINDOW_HEIGHT = SQUARE_SIZE * NUM_SQUARES_HEIGHT
BACKGROUND_COLOR = (0, 128, 0)
LINE_COLOR = BACKGROUND_COLOR
EMPTY_VALUE = 0
MINE_VALUE = 1
MINES_BACKGROUND_COLOR = (24, 24, 24)
# FLAG_MEASUREMENTS
FlAG_PNG = pygame.image.load("soldier.png")
FLAG_WIDTH = FlAG_PNG.get_width()
FLAG_HEIGHT = FlAG_PNG.get_height()
FLAG_START_POS = (WINDOW_WIDTH - FLAG_WIDTH, WINDOW_HEIGHT - FLAG_HEIGHT)

BUSH_PNG = pygame.image.load("grass.png")
BUSH_WIDTH = BUSH_PNG.get_width()
BUSH_HEIGHT = BUSH_PNG.get_height()

MINE_PNG = pygame.image.load("mine.png")
MINE_WIDTH = MINE_PNG.get_width()
MINE_HEIGHT = MINE_PNG.get_height()

RUNNING_STATE = 0
LOSE_STATE = 1
WIN_STATE = 2
ENTER_STATE = 3

SECOND = 1000
